log_dir: '/mnt/e/log'
out_dir: '/mnt/e/3dp/gf/bins/3dpy'

# yacv preview colors, '#RRGGBB' or '#RRGGBBAA' (quoted bc # -> comment)
# defaults
# color_faces: '#ffbf00'
# color_edges: '#1a1aff'

color_faces: '#1E1C31'
color_edges: '#CBE3E7'
